server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    banner-mode: off

  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/ssm?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: mysql2003
      driver-class-name: com.mysql.cj.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
      enable: true

  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        enabled: true
    timeout: 6000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    banner: false
  type-aliases-package: com.ecjtu.dto.pojo





